import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"

import Navbar from "./components/Navbar";
import { monserrat } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>
        <>
          <div>
            <Navbar />
          </div>
          <div>{children}</div>
        </>
      </body>
    </html>
  );
}
